version: "3.8"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks/:/opt/jupyter/notebooks/
      - ./data/:/opt/jupyter/data/
      - ./results/:/opt/jupyter/results/